// <auto-generated />
using System;
using BlueSkyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueSkyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002102340_AddCapacityToApartment")]
    partial class AddCapacityToApartment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlueSkyApp.Data.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    b.HasKey("ApartmentId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InventoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"), 1L, 1);

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("ApartmentID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("BlueSkyApp.Data.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("BlueSkyApp.Data.OrganizationMember", b =>
                {
                    b.Property<int>("OrganizationMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizationMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationMemberId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrganizationMemberId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.HasKey("PropertyId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"), 1L, 1);

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("ApartmentID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.HasKey("ReservationId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F66A74A98B")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"), 1L, 1);

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int")
                        .HasColumnName("ApartmentID");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.Property<string>("TaskType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaskId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("PropertyId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("BlueSkyApp.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534653F4939")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Apartment", b =>
                {
                    b.HasOne("BlueSkyApp.Data.Property", "Property")
                        .WithMany("Apartments")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("FK__Apartment__Prope__46E78A0C");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Inventory", b =>
                {
                    b.HasOne("BlueSkyApp.Data.Apartment", "Apartment")
                        .WithMany("Inventories")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK__Inventory__Apart__4AB81AF0");

                    b.HasOne("BlueSkyApp.Data.Property", "Property")
                        .WithMany("Inventories")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("FK__Inventory__Prope__4BAC3F29");

                    b.Navigation("Apartment");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BlueSkyApp.Data.OrganizationMember", b =>
                {
                    b.HasOne("BlueSkyApp.Data.Organization", "Organization")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK__Organizat__Organ__3E52440B");

                    b.HasOne("BlueSkyApp.Data.Role", "Role")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_OrganizationMembers_Roles");

                    b.HasOne("BlueSkyApp.Data.User", "User")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Organizat__UserI__3F466844");

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Property", b =>
                {
                    b.HasOne("BlueSkyApp.Data.Organization", "Organization")
                        .WithMany("Properties")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK__Propertie__Organ__4316F928");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Reservation", b =>
                {
                    b.HasOne("BlueSkyApp.Data.Apartment", "Apartment")
                        .WithMany("Reservations")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK__Reservati__Apart__571DF1D5");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Task", b =>
                {
                    b.HasOne("BlueSkyApp.Data.Apartment", "Apartment")
                        .WithMany("Tasks")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK__Tasks__Apartment__5070F446");

                    b.HasOne("BlueSkyApp.Data.User", "AssignedToNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__Tasks__AssignedT__52593CB8");

                    b.HasOne("BlueSkyApp.Data.Property", "Property")
                        .WithMany("Tasks")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("FK__Tasks__PropertyI__5165187F");

                    b.Navigation("Apartment");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Apartment", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Reservations");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Organization", b =>
                {
                    b.Navigation("OrganizationMembers");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Property", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Inventories");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BlueSkyApp.Data.Role", b =>
                {
                    b.Navigation("OrganizationMembers");
                });

            modelBuilder.Entity("BlueSkyApp.Data.User", b =>
                {
                    b.Navigation("OrganizationMembers");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
